name: PhigrosPlayer Auto Unpack

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: py3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: build
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python tool-download-lastestpgr.py -c > pgrurl.txt
          set /p PGRURL=<pgrurl.txt
          powershell curl -o pgr.apk %PGRURL%
          python tool-unpack.py pgr.apk
          .\7z a unpack_result.zip unpack-result\*
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}\src\unpack_result.zip